### Numpy
#### One dimesional array

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [8]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [9]:
np.arange(1,47,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [10]:
np.zeros(5)   #for generating zeros of float data type

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [12]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [13]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(15,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.ones((2,3),int)  

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
np.ones((2,3)) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.zeros((2,10),int)        #

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(3,2)

array([[0.67473316, 0.6018616 ],
       [0.54093974, 0.53034472],
       [0.14416704, 0.1156251 ]])

In [27]:
np.random.randn(5,4)

array([[-0.70249774, -0.65492766, -0.01598833,  1.49628349],
       [-1.5159201 ,  0.60139732, -0.59058207,  0.8676417 ],
       [-0.88924107, -0.85573968, -1.01833004,  0.03649411],
       [-0.7931582 ,  0.5709376 , -0.34327765,  1.43990472],
       [ 1.23685583,  0.62773618, -0.32225889, -0.18503725]])

In [28]:
np.random.randint(34,90)

36

In [29]:
np.random.randint(20,199,50)

array([137,  78, 151, 164,  61, 190, 108, 102, 165,  92,  94,  45,  22,
        39, 127,  44,  26,  61,  23,  38, 162, 180, 152, 196, 174,  62,
       111, 119,  38,  76, 145,  74, 183,  32,  52,  77,  94,  26, 113,
        72,  22,  89, 186,  38,  54,  59, 139,  22,  55,  87])

In [30]:
sample_array=np.arange(40)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [31]:
rand_array=np.random.randint(20,90,30)
rand_array

array([31, 55, 49, 41, 20, 26, 67, 49, 23, 31, 39, 26, 26, 32, 78, 69, 70,
       41, 30, 59, 43, 30, 28, 41, 51, 26, 44, 21, 51, 71])

In [34]:
sample_array.reshape(8,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [35]:
rand_array.min()

20

In [36]:
rand_array.argmin()

4

In [37]:
rand_array.max()

78

In [38]:
rand_array.argmax()

14

In [40]:
sample_array.dtype()

dtype('int32')

In [41]:
sample_array.dtype()

TypeError: 'numpy.dtype[int32]' object is not callable

In [42]:
a=np.eye(3)

In [43]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
a.T         #for transpose

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
a=np.random.rand(2,3)
a

array([[0.46880436, 0.15871019, 0.29366749],
       [0.00915052, 0.04305116, 0.5977626 ]])

In [46]:
a.T

array([[0.46880436, 0.00915052],
       [0.15871019, 0.04305116],
       [0.29366749, 0.5977626 ]])

In [47]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
sample_array[3]

13

In [49]:
sample_array[5:7]

array([15, 16])

In [51]:
sample_array[2:7]=100
sample_array

array([ 10,  11, 100, 100, 100, 100, 100,  17,  18,  19,  20])

In [52]:
sample_array[:]=1000
sample_array

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [54]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
sample_array[2:7]

array([12, 13, 14, 15, 16])

In [56]:
subset_sample_array=sample_array[2:7]
subset_sample_array

array([12, 13, 14, 15, 16])

In [57]:
subset_sample_array[1:5]=1000
subset_sample_array

array([  12, 1000, 1000, 1000, 1000])