### Two Domensional Array

In [1]:
import numpy as np

In [2]:
sample_matrix=np.array([[23,45,6],[19,23,56],[2,3,4]])
sample_matrix

array([[23, 45,  6],
       [19, 23, 56],
       [ 2,  3,  4]])

In [4]:
sample_matrix[2][2]

4

In [5]:
sample_matrix[2]

array([2, 3, 4])

In [7]:
sample_matrix[:,(2,2)]

array([[ 6,  6],
       [56, 56],
       [ 4,  4]])

In [9]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [10]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [11]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [12]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [13]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [14]:
np.max(sample_array)

19

In [15]:
np.min(sample_array)

1

In [16]:
np.argmin(sample_array)

0

In [17]:
np.argmax(sample_array)

18

In [19]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [20]:
np.std(sample_array)

5.477225575051661

In [21]:
np.var(sample_array)

30.0

In [22]:
np.mean(sample_array)

10.0

In [23]:
array=np.random.randn(3,4)
array

array([[-0.16924777,  1.14087945,  0.43087381,  0.29057327],
       [-0.16589547,  0.06813601,  0.61696669, -0.86871545],
       [ 1.02825012, -1.07612766,  0.98574101, -0.25470843]])

In [25]:
np.round(array,decimals=3)    #round off

array([[-0.169,  1.141,  0.431,  0.291],
       [-0.166,  0.068,  0.617, -0.869],
       [ 1.028, -1.076,  0.986, -0.255]])

In [27]:
sport=np.array(['golf','cricket','football','cricket','golf'])
np.unique(sport)

array(['cricket', 'football', 'golf'], dtype='<U8')

In [29]:
import pandas as pd
import numpy as np

In [31]:
labels=['w','x','y','z']
sample_list=[100,200,300,400]
array=np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40}

In [33]:
pd.Series(data=array)

0    1
1    2
2    3
3    4
dtype: int32

In [34]:
pd.Series(data=sample_list,index=labels)

w    100
x    200
y    300
z    400
dtype: int64

In [35]:
pd.Series(sample_list,array)

1    100
2    200
3    300
4    400
dtype: int64

In [36]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

In [40]:
sports1=pd.Series([1,2,3,4], index=['cricket','football','golf','baskestball'])
sports1

cricket        1
football       2
golf           3
baskestball    4
dtype: int64

In [41]:
sports1['cricket']

1

In [42]:
sports2=pd.Series([11,2,3,4], index=['cricket','football','golf','baskestball'])
sports2

cricket        11
football        2
golf            3
baskestball     4
dtype: int64

In [43]:
sports1+sports2 

cricket        12
football        4
golf            6
baskestball     8
dtype: int64

In [44]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(), columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.700116  0.975350  0.566106  0.896524  0.590639
B  0.648347  0.451110  0.201836  0.846577  0.433493
C  0.623015  0.708958  0.567064  0.344798  0.158853
D  0.290120  0.218726  0.886152  0.678129  0.743980
E  0.148682  0.245433  0.924697  0.335045  0.524160
F  0.061152  0.107653  0.836105  0.543170  0.293935
G  0.347179  0.333606  0.581341  0.855615  0.743030
H  0.459795  0.110588  0.932682  0.574173  0.766808

In [45]:
df1['score1']

A    0.700116
B    0.648347
C    0.623015
D    0.290120
E    0.148682
F    0.061152
G    0.347179
H    0.459795
Name: score1, dtype: float64

In [52]:
df1[["score1","score2","score3"]]

score1    score2    score3
A  0.700116  0.975350  0.566106
B  0.648347  0.451110  0.201836
C  0.623015  0.708958  0.567064
D  0.290120  0.218726  0.886152
E  0.148682  0.245433  0.924697
F  0.061152  0.107653  0.836105
G  0.347179  0.333606  0.581341
H  0.459795  0.110588  0.932682

In [53]:
df1['score6']=df1['score1']+df1['score2']
df1

score1    score2    score3    score4    score5    score6
A  0.700116  0.975350  0.566106  0.896524  0.590639  1.675466
B  0.648347  0.451110  0.201836  0.846577  0.433493  1.099457
C  0.623015  0.708958  0.567064  0.344798  0.158853  1.331973
D  0.290120  0.218726  0.886152  0.678129  0.743980  0.508846
E  0.148682  0.245433  0.924697  0.335045  0.524160  0.394115
F  0.061152  0.107653  0.836105  0.543170  0.293935  0.168806
G  0.347179  0.333606  0.581341  0.855615  0.743030  0.680785
H  0.459795  0.110588  0.932682  0.574173  0.766808  0.570383

In [54]:
df2={"ID":['101','102','103','104','107'], "Name":["shashank","sandeep","akshay","aayush","Sujeet"],"Profit":[20,34,59,90,67]}
df=pd.DataFrame(df2)
df

ID      Name  Profit
0  101  shashank      20
1  102   sandeep      34
2  103    akshay      59
3  104    aayush      90
4  107    Sujeet      67

In [55]:
df['ID']

0    101
1    102
2    103
3    104
4    107
Name: ID, dtype: object

In [57]:
df[['ID','Name']]

ID      Name
0  101  shashank
1  102   sandeep
2  103    akshay
3  104    aayush
4  107    Sujeet

In [60]:
df.drop("ID",axis=1)

KeyError: "['ID'] not found in axis"

In [61]:
df.drop(3)

Name  Profit
0  shashank      20
1   sandeep      34
2    akshay      59
4    Sujeet      67

In [62]:
df.drop(2,axis=0)

Name  Profit
0  shashank      20
1   sandeep      34
3    aayush      90
4    Sujeet      67